name: realestate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  intl: ^0.20.2
  video_player: ^2.10.0
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  file_picker: ^10.3.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/videos/hompagevideo2.webm
    - assets/images/buy.webp
    - assets/images/rent.webp
    - assets/images/sell.webp

